### ISSUE TITLE
Extension doesn't work with 3.34.5

### ISSUE THREAD

**Issue by olea** [user501254/TouchpadIndicator#50]
Hi:

I'm using Fedora 31 + GNOME 3.34.6 and GNOME Shell 3.34.5 and with xinput installed and X11 session:

> gnome-shell-3.34.5-1.fc31.x86_64
> xorg-x11-server-utils-7.7-32.fc31.x86_64

The extension doesn't work any more.

I've followed your instructions for installing the last version from sources:

> rm -rf ~/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt;
> git clone --depth=1 "https://github.com/user501254/TouchpadIndicator.git" ~/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt;

After relauching GNOME Shell trying to activate the extension gives an error. The log error provided by the Extensions application is:

```
TypeError: this.pointingDevices.filter is not a function

Stack trace:
  _filterByType@/home/olea/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/xinput.js:171:43
  _populateDebugTab@/home/olea/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:181:25
  TouchpadIndicatorSettings@/home/olea/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:61:9
  buildPrefsWidget@/home/olea/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:242:20
  _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
  vfunc_command_line@resource:///org/gnome/shell/extensionPrefs/main.js:351:23
  main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
  @<main>:1:43
  
```

Now I have permanently disabled touchpad and trackpad and only can work with a mouse. Previously it worked fine, probably broke after updating some application but I can't provide the detail.

I would be happy to just recover the trackpad/touchpad use without the extension but I don't know how. I tried this but with no success:

> $ xinput list|grep Synaptics
>⎜   ↳ Synaptics TM2937-001                    	id=13	[slave  pointer  (2)]
> $  xinput set-prop 13 "Device Enabled" 1

---
**Mandatory system details** (please complete/update the following information)
 - **Operating System:** Fedora 31 (Workstation Edition)
 - **Touchpad Indicator extension version:** git master version at 20200511
 - **Gnome Shell version:** GNOME Shell 3.34.5
 - **Display server:** X11 
 - **Switching method:** no idea
 - **Installation source:** github sources

 ---
 

- **X input devices** (ie. output for `xinput list`)  

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Synaptics TM2937-001                    	id=13	[slave  pointer  (2)]
⎜   ↳ Logitech Wireless Mouse                 	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=11	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=12	[slave  keyboard (3)]
```

--- 

Thanks in advance.

**Comment by user501254** [comment]
Please note the output for `gsettings --schemadir ~/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/schemas list-recursively org.gnome.shell.extensions.touchpad-indicator` and post it here.

Next, remove the extension using `rm -rf ~/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt;` and restart the GNOME Shell (use shortcut or logout and log back in)

To enable the touchpad try using `gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled`. This changes the system's settings controlling the touchpad.
Then retry the `xinput set-prop $ID "Device Enabled" 1` command using the correct device id from `xinput --list`.

Also, try installing the version from https://extensions.gnome.org/extension/131/touchpad-indicator/ and let me know in case you face the same issue. The GitHub version have had some recent changes that might not work well with older systems.

**Comment by olea** [comment]
Reinstalled from  https://extensions.gnome.org/extension/131/touchpad-indicator/

Now it works as expected, but needed to restart the session. The GNOME Shell «r» restart didn't worked for some reason.

Thank you!
